GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJIZWxtaSIsImVtYWlsIjoiaGVsbWlAZ21haWwuY29tIiwiaWF0IjoxNzI3NzI5Njk1LCJleHAiOjE3Mjc3Mjk3MTV9.RFpFTEacY3qygmRbiKt7HP-Hoqf1-ZaUUW40PPG4F0k

###
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Helmi 2",
  "email": "helmi2@gmail.com",
  "password": "123456",
  "confirmPassword": "1234567"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "helmi@gmail.com",
  "password": "1234567"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout